import type {
  Conversation,
  ConversationWithRelations,
  Customer,
  Message,
  Order,
  OrderItem,
  OrderWithRelations,
  Product,
  Settings,
} from "@/lib/types";

const now = new Date();
const yesterday = new Date(now);
yesterday.setDate(now.getDate() - 1);
yesterday.setHours(23, 20, 0, 0);

const today = new Date(now);
today.setHours(7, 35, 0, 0);

function iso(date: Date) {
  return date.toISOString();
}

function daysFromNow(days: number) {
  const date = new Date(now);
  date.setDate(now.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export const initialProducts: Product[] = [
  {
    id: "prod_salmon",
    name: "סלמון",
    aliases: ["סלומון", "salmon", "סלמון טרי"],
    cut_options: ["פילה", "פילה בלי עור", "פילה עם עור", "קוביות", "סביצ׳ה", "פרוסות"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_denis",
    name: "דניס",
    aliases: ["דניסים", "denis"],
    cut_options: ["שלם", "נקי", "פילה", "לשבת"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_bass",
    name: "לברק",
    aliases: ["לברקים", "sea bass"],
    cut_options: ["שלם", "נקי", "פילה", "פרוסות", "לשבת"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_tuna",
    name: "טונה",
    aliases: ["tuna", "טונה טרייה"],
    cut_options: ["סביצ׳ה", "קוביות", "סטייק"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_mullet",
    name: "בורי",
    aliases: ["בורי טרי"],
    cut_options: ["שלם", "נקי", "פרוסות", "פילה"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_tilapia",
    name: "מושט",
    aliases: ["אמנון", "מושטים"],
    cut_options: ["שלם", "נקי", "פרוסות", "פילה"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_nile",
    name: "נסיכת הנילוס",
    aliases: ["נסיכה", "נילוס"],
    cut_options: ["פילה", "קוביות", "פרוסות"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_ceviche",
    name: "סביצ׳ה",
    aliases: ["סביצ'ה", "סביצה", "מגש סביצ׳ה"],
    cut_options: ["מגש", "קוביות", "מוכן להגשה"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_hraime",
    name: "חריימה",
    aliases: ["חרימה", "דג לחריימה"],
    cut_options: ["מוכן לבישול", "פרוסות"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
  {
    id: "prod_patties",
    name: "קציצות דגים",
    aliases: ["קציצות", "קציצות דג"],
    cut_options: ["מוכן לבישול", "טחון"],
    active: true,
    created_at: iso(now),
    updated_at: iso(now),
  },
];

export const defaultSettings: Settings = {
  id: "settings_default",
  business_name: "בון חכם Demo",
  opening_hours: {
    "א-ה": "08:00-18:00",
    שישי: "07:00-14:30",
    שבת: "סגור",
  },
  pickup_windows: ["08:00-10:00", "10:00-12:00", "12:00-14:00"],
  after_hours_auto_reply: "קיבלנו את ההזמנה. החנות תאשר אותה בשעות הפעילות.",
  minimum_confidence_threshold: 85,
  require_human_approval: true,
  default_ai_order_status: "pending_review",
  created_at: iso(now),
  updated_at: iso(now),
};

export const sampleMessages = [
  {
    name: "משה לוי",
    phone: "052-1234567",
    text: "שלום, אני רוצה 2 קילו סלמון פילה בלי עור, חצי קילו טונה לסביצ׳ה, שיהיה מוכן לשישי ב־10:30. משה 052-1234567",
  },
  {
    name: "דני כהן",
    phone: "052-4442211",
    text: "תכין לי כמו שבוע שעבר, אבל קצת יותר סלמון, לשישי בבוקר",
  },
  {
    name: "רחל",
    phone: "050-2222222",
    text: "4 דניסים נקיים וחריימה ל־11, רחל 050-2222222",
  },
  {
    name: "יואב",
    phone: "053-3333344",
    text: "אני צריך לברק וסלמון למחר, תעדכן כמה עולה",
  },
  {
    name: "נועה",
    phone: "054-9090901",
    text: "אפשר להזמין 3 מגשים של סביצ׳ה לשישי ב־9?",
  },
  {
    name: "אבי",
    phone: "054-1111111",
    text: "2 קילו מושט פרוס, קילו סלמון בלי עור, לאסוף ב-12:30, אבי 054-1111111",
  },
];

export const customers: Customer[] = [
  {
    id: "cust_moshe",
    name: "משה לוי",
    phone: "0521234567",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "cust_rachel",
    name: "רחל בן דוד",
    phone: "0502222222",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "cust_dani",
    name: "דני כהן",
    phone: "0524442211",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "cust_noa",
    name: "נועה",
    phone: "0549090901",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "cust_avi",
    name: "אבי",
    phone: "0541111111",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
];

export const conversations: Conversation[] = [
  {
    id: "conv_moshe",
    customer_id: "cust_moshe",
    phone: "0521234567",
    status: "open",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "conv_rachel",
    customer_id: "cust_rachel",
    phone: "0502222222",
    status: "open",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "conv_dani",
    customer_id: "cust_dani",
    phone: "0524442211",
    status: "needs_review",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "conv_noa",
    customer_id: "cust_noa",
    phone: "0549090901",
    status: "missing_details",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "conv_avi",
    customer_id: "cust_avi",
    phone: "0541111111",
    status: "open",
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
];

export const messages: Message[] = [
  {
    id: "msg_moshe_in",
    conversation_id: "conv_moshe",
    direction: "incoming",
    text: "שלום, אני רוצה 2 קילו סלמון פילה בלי עור, חצי קילו טונה לסביצ׳ה, שיהיה מוכן לשישי ב־10:30. משה 052-1234567",
    timestamp: iso(yesterday),
    source: "simulator",
    created_at: iso(yesterday),
  },
  {
    id: "msg_moshe_out",
    conversation_id: "conv_moshe",
    direction: "outgoing",
    text: "קיבלנו את ההזמנה שלך. היא נכנסה למערכת ותעבור לאישור החנות בבוקר.",
    timestamp: iso(new Date(yesterday.getTime() + 30000)),
    source: "system",
    created_at: iso(new Date(yesterday.getTime() + 30000)),
  },
  {
    id: "msg_rachel_in",
    conversation_id: "conv_rachel",
    direction: "incoming",
    text: "4 דניסים נקיים וחריימה ל־11, רחל 050-2222222",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 15)),
    source: "simulator",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 15)),
  },
  {
    id: "msg_rachel_out",
    conversation_id: "conv_rachel",
    direction: "outgoing",
    text: "קיבלנו את ההזמנה שלך. היא נכנסה למערכת ותעבור לאישור החנות בבוקר.",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 16)),
    source: "system",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 16)),
  },
  {
    id: "msg_dani_in",
    conversation_id: "conv_dani",
    direction: "incoming",
    text: "תכין לי כמו שבוע שעבר, אבל קצת יותר סלמון, לשישי בבוקר",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 50)),
    source: "simulator",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 50)),
  },
  {
    id: "msg_dani_out",
    conversation_id: "conv_dani",
    direction: "outgoing",
    text: "קיבלנו את הבקשה, אבל ההזמנה דורשת בדיקה של החנות כי היא מתייחסת להזמנה קודמת.",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 51)),
    source: "system",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 51)),
  },
  {
    id: "msg_noa_in",
    conversation_id: "conv_noa",
    direction: "incoming",
    text: "אפשר להזמין 3 מגשים של סביצ׳ה לשישי ב־9?",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 80)),
    source: "simulator",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 80)),
  },
  {
    id: "msg_noa_out",
    conversation_id: "conv_noa",
    direction: "outgoing",
    text: "אפשר. אפשר לקבל שם מלא וטלפון לרישום ההזמנה?",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 81)),
    source: "system",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 81)),
  },
  {
    id: "msg_avi_in",
    conversation_id: "conv_avi",
    direction: "incoming",
    text: "2 קילו מושט פרוס, קילו סלמון בלי עור, לאסוף ב-12:30, אבי 054-1111111",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 120)),
    source: "simulator",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 120)),
  },
  {
    id: "msg_avi_out",
    conversation_id: "conv_avi",
    direction: "outgoing",
    text: "קיבלנו את ההזמנה שלך. היא נכנסה למערכת ותעבור לאישור החנות בבוקר.",
    timestamp: iso(new Date(yesterday.getTime() + 1000 * 60 * 121)),
    source: "system",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 121)),
  },
];

export const orders: Order[] = [
  {
    id: "order_1001",
    order_number: "ORD-1001",
    customer_id: "cust_moshe",
    conversation_id: "conv_moshe",
    status: "pending_review",
    pickup_date: daysFromNow(5),
    pickup_date_text: "שישי",
    pickup_time: "10:30",
    urgency: "normal",
    raw_messages: [messages[0].text],
    ai_confidence: 94,
    missing_fields: [],
    human_review_required: false,
    notes: "לא לערבב בשקית אחת",
    customer_notes: null,
    created_at: iso(yesterday),
    updated_at: iso(today),
  },
  {
    id: "order_1002",
    order_number: "ORD-1002",
    customer_id: "cust_rachel",
    conversation_id: "conv_rachel",
    status: "pending_review",
    pickup_date: daysFromNow(5),
    pickup_date_text: "שישי",
    pickup_time: "11:00",
    urgency: "normal",
    raw_messages: [messages[2].text],
    ai_confidence: 87,
    missing_fields: [],
    human_review_required: false,
    notes: null,
    customer_notes: "לרחל חשוב ניקוי יסודי",
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 15)),
    updated_at: iso(today),
  },
  {
    id: "order_1003",
    order_number: "ORD-1003",
    customer_id: "cust_dani",
    conversation_id: "conv_dani",
    status: "human_review",
    pickup_date: daysFromNow(5),
    pickup_date_text: "שישי בבוקר",
    pickup_time: null,
    urgency: "normal",
    raw_messages: [messages[4].text],
    ai_confidence: 48,
    missing_fields: ["quantity", "pickup_time"],
    human_review_required: true,
    notes: "מתייחס להזמנה קודמת, צריך לבדוק היסטוריה לפני אישור.",
    customer_notes: null,
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 50)),
    updated_at: iso(today),
  },
  {
    id: "order_1004",
    order_number: "ORD-1004",
    customer_id: "cust_noa",
    conversation_id: "conv_noa",
    status: "missing_details",
    pickup_date: daysFromNow(5),
    pickup_date_text: "שישי",
    pickup_time: "09:00",
    urgency: "normal",
    raw_messages: [messages[6].text],
    ai_confidence: 78,
    missing_fields: ["customer_name", "phone"],
    human_review_required: true,
    notes: null,
    customer_notes: null,
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 80)),
    updated_at: iso(today),
  },
  {
    id: "order_1005",
    order_number: "ORD-1005",
    customer_id: "cust_avi",
    conversation_id: "conv_avi",
    status: "approved",
    pickup_date: daysFromNow(1),
    pickup_date_text: "מחר",
    pickup_time: "12:30",
    urgency: "normal",
    raw_messages: [messages[8].text],
    ai_confidence: 91,
    missing_fields: [],
    human_review_required: false,
    notes: null,
    customer_notes: null,
    created_at: iso(new Date(yesterday.getTime() + 1000 * 60 * 120)),
    updated_at: iso(today),
  },
];

export const orderItems: OrderItem[] = [
  {
    id: "item_1001_1",
    order_id: "order_1001",
    product_name: "סלמון",
    quantity: 2,
    unit: "kg",
    cut_style: "פילה בלי עור",
    notes: "",
    created_at: iso(yesterday),
  },
  {
    id: "item_1001_2",
    order_id: "order_1001",
    product_name: "טונה",
    quantity: 0.5,
    unit: "kg",
    cut_style: "סביצ׳ה",
    notes: "",
    created_at: iso(yesterday),
  },
  {
    id: "item_1002_1",
    order_id: "order_1002",
    product_name: "דניס",
    quantity: 4,
    unit: "unit",
    cut_style: "נקי",
    notes: "",
    created_at: iso(yesterday),
  },
  {
    id: "item_1002_2",
    order_id: "order_1002",
    product_name: "חריימה",
    quantity: null,
    unit: "unknown",
    cut_style: "מוכן לבישול",
    notes: "לא צוינה כמות מדויקת",
    created_at: iso(yesterday),
  },
  {
    id: "item_1003_1",
    order_id: "order_1003",
    product_name: "סלמון",
    quantity: null,
    unit: "unknown",
    cut_style: null,
    notes: "כמו שבוע שעבר, קצת יותר",
    created_at: iso(yesterday),
  },
  {
    id: "item_1004_1",
    order_id: "order_1004",
    product_name: "סביצ׳ה",
    quantity: 3,
    unit: "tray",
    cut_style: "מגש",
    notes: "",
    created_at: iso(yesterday),
  },
  {
    id: "item_1005_1",
    order_id: "order_1005",
    product_name: "מושט",
    quantity: 2,
    unit: "kg",
    cut_style: "פרוסות",
    notes: "",
    created_at: iso(yesterday),
  },
  {
    id: "item_1005_2",
    order_id: "order_1005",
    product_name: "סלמון",
    quantity: 1,
    unit: "kg",
    cut_style: "פילה בלי עור",
    notes: "",
    created_at: iso(yesterday),
  },
];

export function hydrateOrders(
  sourceOrders = orders,
  sourceCustomers = customers,
  sourceConversations = conversations,
  sourceMessages = messages,
  sourceItems = orderItems,
): OrderWithRelations[] {
  return sourceOrders.map((order) => ({
    ...order,
    customer: sourceCustomers.find((customer) => customer.id === order.customer_id) ?? null,
    conversation:
      sourceConversations.find((conversation) => conversation.id === order.conversation_id) ?? null,
    items: sourceItems.filter((item) => item.order_id === order.id),
    messages: sourceMessages.filter((message) => message.conversation_id === order.conversation_id),
  }));
}

export function hydrateConversations(
  sourceConversations = conversations,
  sourceCustomers = customers,
  sourceMessages = messages,
  sourceOrders = hydrateOrders(),
): ConversationWithRelations[] {
  return sourceConversations.map((conversation) => ({
    ...conversation,
    customer: sourceCustomers.find((customer) => customer.id === conversation.customer_id) ?? null,
    messages: sourceMessages.filter((message) => message.conversation_id === conversation.id),
    orders: sourceOrders.filter((order) => order.conversation_id === conversation.id),
  }));
}
